name: CI

# on:
#   push:
#     branches:
#       - main

on:
  release:
    types: [released]

jobs:
  AAA:
    env:
      EEH_SERVER: 172.28.0.10

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: get tag
        run: |
          echo "Tag: ${{ github.event.release.tag_name }}"
          
          echo "$IMAGE_VERSION" > eeh-version
          echo "Fininshed Verison stuff"

      - name: Patch build info
        run: |
          sed -i 's/VERSION_NOT_SET/${{ github.event.release.tag_name }}/' application.conf
          sed -i 's/SHA_NOT_SET/${{ github.sha }}/' application.conf
          sed -i "s/BUILD_DATE_NOT_SET/$(date -u +"%Y-%m-%dT%H:%M:%SZ")/" application.conf

          cat application.conf

      - name: Install Open VPN
        run: sudo apt --assume-yes --no-install-recommends install openvpn

      - name: Init VPN
        run: |
          echo "${{ secrets.EEH_OVPN_FILE }}" > eeh.ovpn
          echo "${{ secrets.EEH_OVPN_CREDS }}" > vpn-creds.txt
          sudo openvpn --config "eeh.ovpn" --log "vpn.log" --daemon --auth-user-pass vpn-creds.txt
          until ping -c1 ${{ env.EEH_SERVER }}; do sleep 1; done

      - name: Deploy
        run: |
          echo "${{ secrets.EEH_SSH_KEY }}" > eeh_ssh_key
          chmod 400 eeh_ssh_key
          ssh -o StrictHostKeyChecking=no -i eeh_ssh_key spadger@172.28.0.10 "sed -i 's/^\(IMAGE=ghcr.io\/eehackspace\/access-control:\).*/\1${{ github.event.release.tag_name }}/' z.sh"
          ssh -o StrictHostKeyChecking=no -i eeh_ssh_key spadger@172.28.0.10 "./z.sh &"
        
      - name: Kill VPN connection
        if: always()
        run: |
          sudo chmod 777 vpn.log
          sudo killall openvpn      

