name: CI

on:
  release:
    types: [released]


jobs:
  AAA:
    runs-on: ubuntu-latest
    steps:

      - name: get tag
        run: |
          echo "Tag: ${{ toJSON(github) }}"
          
          echo "$IMAGE_VERSION" > eeh-version
          echo "Fininshed Verison stuff"


