name: CI

on:
  push:
    branches:
      - main

jobs:
  AAA:
    env:
      EEH_SERVER: 172.28.0.10

    runs-on: ubuntu-latest
    steps:

      - name: get tag
        run: |
          echo "Tag: ${{ github.event.release.tag_name }}"
          
          echo "$IMAGE_VERSION" > eeh-version
          echo "Fininshed Verison stuff"

      - name: Install Open VPN
        run: sudo apt --assume-yes --no-install-recommends install openvpn

      - name: Setup VPN config
        run: |
          echo "${{ secrets.EEH_OVPN_FILE }}" > eeh.ovpn
          echo "${{ secrets.EEH_OVPN_CREDS }}" > vpn-creds.txt
          echo "${{ secrets.EEH_SSH_KEY }}" > ~/.ssh/id_rsa
          
      - name: Connect VPN
        timeout-minutes: 1
        run: |
          sudo openvpn --config "eeh.ovpn" --log "vpn.log" --daemon --auth-user-pass vpn-creds.txt
          until ping -c1 ${{ env.EEH_SERVER }}; do sleep 1; done

      - name: deploy
        run: ssh spadger@172.28.0.10 "ls -lah"
        
      - name: Kill VPN connection
        if: always()
        run: |
          sudo chmod 777 vpn.log
          sudo killall openvpn      

