name: CI

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

jobs:
  AAA:
    runs-on: ubuntu-latest
    steps:
      - name: Hello A1
        run: echo "Hello A1"
      
      - name: Calculate version
        id: version
        run: |
          IMAGE_VERSION=$(date +'%Y-%m-%d-%H%M')
          echo "::set-output name=version::$IMAGE_VERSION"


  BBB:
    needs: AAA
    runs-on: ubuntu-latest
    steps:
      - name: Hello B1
        run: echo "Hello B1"
      

      
      - name: Print recovered version
        run: echo "Hello ${{ steps.version.outputs.version }}"

