name: CI

on:
  push:
    branches:
      - main

jobs:
  AAA:
    env:
      EEH_SERVER: 172.28.0.10

    runs-on: ubuntu-latest
    steps:

      - name: get tag
        run: |
          echo "Tag: ${{ github.event.release.tag_name }}"
          
          echo "$IMAGE_VERSION" > eeh-version
          echo "Fininshed Verison stuff"

      - name: Install Open VPN
        run: sudo apt --assume-yes --no-install-recommends install openvpn

      - name: Setup VPN config
        run: |
          echo "${{ secrets.EEH_OVPN_FILE }}" > eeh.ovpn
          echo "${{ secrets.EEH_OVPN_CREDS }}" > secret.txt
          
      - name: Connect VPN
        run: sudo openvpn --config "eeh.ovpn" --log "vpn.log" --daemon

      - name: Wait for a VPN connection
        timeout-minutes: 1
        run: until ping -c1 ${{ env.EEH_SERVER }}; do sleep 2; done
        
      - name: Kill VPN connection
        if: always()
        run: |
          sudo chmod 777 vpn.log
          sudo killall openvpn      

