name: CI

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

jobs:
  AAA:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2

      - name: Hello A1
        run: echo "Hello A1"
      
      - name: Calculate version
        id: version
        run: |
          IMAGE_VERSION=$(date +'%Y-%m-%d-%H%M')
          echo "Version will be $IMAGE_VERSION"
          echo "::set-output name=version::$IMAGE_VERSIONI"
          echo "::set-output name=action_fruit::strawberry"
          echo "Version output is: ${{ steps.version.outputs.version  }}"
          echo "All Steps: ${{ steps.version }}"
          echo "Fininshed Verison stuff"

  BBB:
    needs: AAA
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      
      - name: Hello B1
        run: echo "Hello B1"
      
      - name: Version step
        run: echo "${{ steps.version }}"

      - name: Print version step outputs version
        run: echo "Hello ${{ steps.version.outputs }}"

