name: CI

on:
  push:
    branches: [ main ]

env:
  REGISTRY: ghcr.io

jobs:
  AAA:
    runs-on: ubuntu-latest
    steps:
      - name: Hello A1
        run: echo "Hello A1"
      
      - name: Calculate version
        id: version
        run: |
          IMAGE_VERSION=$(date +'%Y-%m-%d-%H%M')
          echo "Version will be $IMAGE_VERSION"
          echo "::set-output name=version::$IMAGE_VERSIONI"
          echo "Version output is: ${{ steps.version.outputs.version  }}"
          echo "All Steps: ${{ parseJSON(steps)  }}"
          echo "Fininshed Verison stuff"

  BBB:
    needs: AAA
    runs-on: ubuntu-latest
    steps:
      - name: Hello B1
        run: echo "Hello B1"
      
      - name: All Steps
        run: echo "${{ parseJSON(steps) }}"

      - name: Print recovered version
        run: echo "Hello ${{ steps.version.outputs.version }}"

