name: CI

on:
  push:
    branches: [ main ]
    outputs:
      version:
        description: "The first job output"
        value: ${{ jobs.AAA.outputs.version }}

      clanger:
        description: "The second fruity job output"
        value: ${{ jobs.AAA.outputs.compo }}

      foxed:
        description: "The second fruity job output"
        value: ${{ jobs.AAA.outputs.fixed }}
  
  workflow_call:
    outputs:
      version:
        description: "The first job output"
        value: ${{ jobs.AAA.outputs.version }}

      clanger:
        description: "The second fruity job output"
        value: ${{ jobs.AAA.outputs.compo }}

      foxed:
        description: "The second fruity job output"
        value: ${{ jobs.AAA.outputs.fixed }}

env:
  REGISTRY: ghcr.io

jobs:
  AAA:
    outputs:
      fixed: "it is fixed"
      version: ${{ steps.version.outputs.version }}
      compo: ${{ steps.version.outputs.action_fruit }}
    runs-on: ubuntu-latest
    steps:

      - name: Calculate version
        id: version
        run: |
          IMAGE_VERSION=$(date +'%Y-%m-%d-%H%M')
          echo "Version will be $IMAGE_VERSION"
          echo "::set-output name=version::$IMAGE_VERSION"
          echo "::set-output name=action_fruit::strawberry"
          echo "Version output is: ${{ steps.version.outputs.version  }}"
          echo "All Steps: ${{ steps.version }}"
          echo "Fininshed Verison stuff"

  BBB:
    needs: AAA
    runs-on: ubuntu-latest
    steps:
      
      - name: Hello B1
        run: echo "Hello B1 version=|${{ inputs.version }}| compo=|${{ inputs.compo }}| clanger=|${{ inputs.clanger }}| foxed=|${{ inputs.foxed }}|"
      
      - name: Version step
        run: echo "${{ toJSON(github) }}"

      - name: Print version step outputs version
        run: echo "Hello ${{ steps.version.outputs }}"

